# -*- coding: utf-8 -*-
"""Used Car Project-Exploratory analysis

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ikfKm_5GWgFLswyxrYWcj-yB5MuR70rd
"""

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib as plt

from google.colab import files

uploaded = files.upload()

for fn in uploaded.keys():
  print('User uploaded file "{name}" with length {length} bytes'.format(
      name=fn, length=len(uploaded[fn])))

import io

dataset= pd.read_csv(io.StringIO(uploaded['all.csv'].decode('utf-8')))

dataset.head(5)

dataset.shape

dataset.dtypes

!pip install pandas_profiling
import pandas_profiling
pandas_profiling.ProfileReport(dataset)

# Median Price For Each Class
dataset.groupby(['Class'])[['Price']].median()

# Split the dataset and count each class
df_3=dataset.loc[dataset['Class'] == '3-Series']
df_3.shape

df_3['Price'].describe()

df_C=dataset.loc[dataset['Class'] == 'C-Class']
df_C.shape

df_C['Price'].describe()

df_E=dataset.loc[dataset['Class'] == 'E-Class']
df_E.shape

df_E['Price'].describe()

import matplotlib.pyplot as plt
g=sns.heatmap(dataset.corr(),annot=True, fmt='.2f',cmap='Blues')